netsentinel:
  risks:
    database-ports: [1433, 1521, 3306, 5432, 5984]
    services:
      - port: 21
        level: MEDIUM
      - port: 23
        level: HIGH
      - port: 445
        level: HIGH
      - port: 3389
        level: HIGH
      - port: 5900
        level: MEDIUM
      - port: 6379
        level: HIGH
      - port: 27017
        level: HIGH
      - port: 11211
        level: MEDIUM
      - port: 2375
        level: CRITICAL
      - port: 9200
        level: MEDIUM
