import { Injectable, signal } from '@angular/core';

const TR: Record<'es' | 'en', Record<string, string>> = {
  es: {
    'nav.newScan': 'Escanear',
    'nav.dashboard': 'Panel',
    'nav.history': 'Historial',
    'nav.assets': 'Dispositivos',
    'nav.compare': 'Comparar',
    'nav.agent': 'Asistente IA',
    'nav.tutorial': 'Tutorial',
    'nav.credits': 'Creditos',
    'offline.banner': 'NetSentinel esta reactivando su motor local. Puedes esperar unos segundos o abrir la reparacion.',
    'offline.setup': 'Reparar',
    'error.localService.repairing': 'NetSentinel no pudo comunicarse con su motor local. Ya esta intentando reactivarlo automaticamente; deja la app abierta unos segundos y vuelve a intentarlo.',
    'error.localService.internal': 'El motor local respondio, pero tuvo un problema interno. Intenta de nuevo; si se repite, abre Reparar para revisar la instalacion.',
    'error.data.notFound': 'No encontre esa informacion guardada. Es posible que haya sido eliminada o que aun no exista.',
    'error.scan.notFound': 'No encontre ese analisis. Puede haber sido eliminado o no termino de guardarse.',
    'error.scan.engine': 'El motor de analisis no pudo arrancar correctamente. NetSentinel esta intentando recuperarlo; si vuelve a fallar, abre Reparar.',
    'error.scan.timeout': 'El analisis tardo mas de lo esperado. Prueba con el nivel Rapido o revisa que la red este conectada.',
    'error.target.required': 'Escribe o selecciona una red antes de iniciar el analisis.',
    'error.target.invalid': 'La direccion no parece valida. Usa una IP como 192.168.1.1 o una red como 192.168.1.0/24.',
    'error.generic.withRetry': 'No se pudo completar la accion. Intenta de nuevo; si vuelve a pasar, usa Reparar para que NetSentinel revise su motor local.',

    'setup.checking': 'Revisando si tu equipo esta listo...',
    'setup.missing.title': 'Completa la instalacion de NetSentinel',
    'setup.missing.body': 'NetSentinel instalara automaticamente el motor local que analiza tu red. Todo ocurre en tu computadora y no se suben datos del analisis.',
    'setup.installing.title': 'Instalando componentes locales...',
    'setup.installing.body': 'Esto puede tardar varios minutos la primera vez. Mantén esta ventana abierta.',
    'setup.progress.tools': 'Instalando herramientas de analisis...',
    'setup.progress.db': 'Preparando almacenamiento local...',
    'setup.progress.backend': 'Instalando servicio interno...',
    'setup.progress.sandbox': 'Configurando motor seguro de escaneo...',
    'setup.progress.scripts': 'Probando que todo pueda iniciar...',
    'setup.needs_reboot.title': 'Reinicio requerido',
    'setup.needs_reboot.body': 'Se habilitaron las funciones necesarias de Windows. Reinicia el equipo y vuelve a abrir NetSentinel para continuar.',
    'setup.btn.reboot': 'Reiniciar ahora',
    'setup.error.title': 'No se pudo completar la preparacion',
    'setup.error.body': 'NetSentinel no pudo preparar el motor local automaticamente. Intenta de nuevo; si vuelve a fallar, revisaremos los detalles tecnicos.',
    'setup.error.uac': 'La preparacion no arranco. Suele pasar cuando se cancela el permiso de administrador (UAC) que Windows pide al iniciar. Vuelve a intentarlo y acepta la ventana de permisos.',
    'setup.starting.title': 'Iniciando el motor local',
    'setup.starting.body': 'El motor ya esta instalado. Estamos encendiendo el servicio local; esto tarda unos segundos.',
    'setup.dep.backend': 'Servicio interno',
    'setup.dep.sandbox': 'Motor seguro de escaneo',
    'setup.dep.api': 'Aplicacion local',
    'setup.dep.ready': 'Listo',
    'setup.dep.pending': 'Pendiente',
    'setup.btn.retry': 'Intentar de nuevo',
    'setup.ready.title': 'Todo listo',
    'setup.ready.body': 'El motor local esta listo para analizar tu red.',
    'setup.btn.install': 'Completar instalacion',
    'setup.btn.later': 'Continuar sin preparar',
    'setup.btn.verify': 'Verificar estado ahora',
    'setup.btn.continue': 'Analizar mi red',
    'setup.technical.show': 'Ver detalles tecnicos',
    'setup.technical.hide': 'Ocultar detalles tecnicos',
    'setup.nvd.label': 'Acelerar busqueda de vulnerabilidades (opcional)',
    'setup.nvd.hint': 'Una API key gratuita de NVD permite consultar vulnerabilidades mas rapido. Si no la agregas, NetSentinel igual funciona.',
    'setup.nvd.placeholder': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    'setup.nvd.save': 'Guardar',
    'setup.nvd.saved': 'Guardado',

    'scan.title': 'Analizar mi red',
    'scan.subtitle': 'Detecta problemas de seguridad en todos los dispositivos conectados a tu red',
    'scan.network.detecting': 'Detectando tu red...',
    'scan.network.detected': 'Red detectada',
    'scan.network.change': 'Cambiar',
    'scan.network.choose': 'Elige la red que quieres analizar',
    'scan.network.retry': 'Volver a detectar',
    'scan.network.none': 'No se detecto ninguna red automaticamente.',
    'scan.manual.label': 'Direccion de red o dispositivo',
    'scan.manual.placeholder': '192.168.1.0/24  o  192.168.1.1',
    'scan.manual.hint': 'Escribe la IP de tu router o el rango de tu red',
    'scan.manual.link': 'Ingresar manualmente',
    'scan.start': 'Analizar mi red',
    'scan.error.invalidTarget': 'Solo letras, numeros, puntos y guiones',
    'scan.error.startFailed': 'No pude iniciar el analisis. NetSentinel revisara su motor local y puedes intentarlo de nuevo en unos segundos.',
    'scan.error.scanFailed': 'El analisis no pudo completarse. Prueba con el nivel Rapido; si vuelve a fallar, abre Reparar.',
    'scan.error.lostConnection': 'NetSentinel perdio contacto con su motor local. Ya esta intentando reactivarlo automaticamente.',
    'results.error.loadFailed': 'No pude cargar este resultado. Puede que el analisis ya no exista o que el motor local este reiniciandose.',
    'offline.dot': 'Backend no disponible',
    'scan.cancel': 'Cancelar',
    'scan.newScan': 'Nuevo analisis',
    'scan.step.searching': 'Buscando dispositivos en tu red...',
    'scan.step.found': 'Dispositivos encontrados — revisando seguridad...',
    'scan.step.checking': 'Consultando base de datos de vulnerabilidades...',
    'scan.step.analyzing': 'Preparando tu diagnostico de seguridad...',
    'scan.step.web': 'Analizando servicios web...',
    'scan.showDetails': 'Ver progreso tecnico',
    'scan.hideDetails': 'Ocultar detalles',

    'results.risk.critical': 'Tu red tiene problemas criticos',
    'results.risk.critical.sub': 'Requiere atencion inmediata para proteger tu negocio',
    'results.risk.high': 'Tu red tiene riesgos importantes',
    'results.risk.high.sub': 'Actua pronto para proteger tus datos y dispositivos',
    'results.risk.medium': 'Tu red tiene algunos problemas',
    'results.risk.medium.sub': 'Revisa las recomendaciones a continuacion',
    'results.risk.low': 'Tu red esta bien',
    'results.risk.low.sub': 'Solo hay detalles menores que revisar',
    'results.risk.info': 'Tu red esta segura',
    'results.risk.info.sub': 'No se encontraron problemas de seguridad',
    'results.hero.devices': 'dispositivo(s) analizado(s)',
    'results.hero.issues': 'problema(s) encontrado(s)',

    'results.whattodo': 'Que debes hacer',
    'results.problems': 'Problemas encontrados',
    'results.noproblems': 'No se encontraron problemas de seguridad en tu red.',
    'results.technical.toggle': 'Ver detalles tecnicos',
    'results.technical.hide': 'Ocultar detalles tecnicos',
    'results.technical.title': 'Detalles tecnicos — Dispositivos y puertos',
    'results.scanDate': 'Analisis del',
    'results.duration': 'Duracion',

    'severity.critical': 'Critico',
    'severity.high': 'Alto',
    'severity.medium': 'Medio',
    'severity.low': 'Bajo',
    'severity.info': 'Info',

    'results.back': 'Volver',
    'results.live.scanning': 'Analizando tu red...',
    'results.live.starting': 'Iniciando analisis...',
    'results.loading': 'Cargando resultados...',
    'results.noHosts': 'No se encontraron dispositivos en este escaneo.',
    'results.noPorts': 'Sin puertos reportados.',
    'results.col.port': 'Puerto',
    'results.col.state': 'Estado',
    'results.col.service': 'Servicio',
    'results.col.version': 'Version',
    'results.col.cves': 'Vulnerabilidades',
    'results.mac': 'MAC',
    'results.vendor': 'Fabricante',
    'results.openPorts': 'servicio(s) activo(s)',
    'results.cves': 'vulnerabilidad(es)',
    'results.webFindings': 'hallazgo(s) web',
    'results.web.title': 'Hallazgos web',

    'history.title': 'Historial de analisis',
    'history.scans': 'analisis',
    'history.loading': 'Cargando...',
    'history.empty': 'No hay analisis registrados.',
    'history.startFirst': 'Realiza tu primer analisis',
    'history.col.target': 'Red analizada',
    'history.col.status': 'Estado',
    'history.col.started': 'Fecha',
    'history.col.duration': 'Duracion',
    'history.prev': 'Anterior',
    'history.next': 'Siguiente',
    'history.delete': 'Eliminar',
    'history.error': 'No pude cargar el historial. NetSentinel revisara su motor local y puedes intentarlo de nuevo en unos segundos.',

    'status.pending': 'Iniciando',
    'status.running': 'Analizando',
    'status.completed': 'Completado',
    'status.failed': 'Error',
    'status.cancelled': 'Cancelado',

    'scan.profile.label': 'Nivel de analisis',
    'scan.profile.quick': 'Rapido',
    'scan.profile.quick.hint': 'Revision rapida de lo mas comun',
    'scan.profile.standard': 'Estandar',
    'scan.profile.standard.hint': 'Balanceado para la mayoria de redes',
    'scan.profile.full': 'Completo',
    'scan.profile.full.hint': 'Revision profunda, puede tardar bastante',

    'results.export.pdf': 'Exportar como PDF',
    'results.export.json': 'Exportar como JSON',
    'results.export.csv': 'Exportar como CSV',

    'results.finding.status.open': 'Abierto',
    'results.finding.status.acknowledged': 'Revisado',
    'results.finding.status.false_positive': 'Falso positivo',
    'results.finding.status.resolved': 'Resuelto',

    'dashboard.title': 'Panel de control',
    'dashboard.subtitle': 'Resumen de todos los analisis realizados',
    'dashboard.loading': 'Cargando...',
    'dashboard.error': 'No pude cargar el panel. NetSentinel revisara su motor local y puedes intentarlo de nuevo en unos segundos.',
    'dashboard.stat.totalScans': 'Analisis totales',
    'dashboard.stat.completed': 'Completados',
    'dashboard.stat.hosts': 'Dispositivos',
    'dashboard.stat.cves': 'Vulnerabilidades',
    'dashboard.stat.avgRisk': 'Riesgo promedio',
    'dashboard.stat.active': 'En curso',
    'dashboard.cvesByLevel': 'Vulnerabilidades por nivel',
    'dashboard.recentScans': 'Analisis recientes',
    'dashboard.noScans': 'Aun no hay analisis. Realiza tu primer escaneo.',
    'dashboard.hosts': 'dispositivos',

    'compare.title': 'Comparar analisis',
    'compare.subtitle': 'Compara dos analisis para ver como cambio tu red',
    'compare.scanA': 'Analisis A',
    'compare.scanB': 'Analisis B',
    'compare.choose': 'Seleccionar...',
    'compare.run': 'Comparar',
    'compare.new': 'Nuevos',
    'compare.resolved': 'Resueltos',
    'compare.persistent': 'Persistentes',
    'compare.noFindings': 'Los dos analisis son identicos — no hay diferencias.',
    'compare.error': 'No pude comparar esos analisis. Revisa que ambos existan y vuelve a intentarlo.',

    'assets.title': 'Dispositivos',
    'assets.subtitle': 'Todos los dispositivos detectados en tus analisis',
    'assets.loading': 'Cargando...',
    'assets.empty': 'Aun no hay dispositivos registrados. Realiza un analisis primero.',
    'assets.error': 'No pude cargar los dispositivos guardados. NetSentinel revisara su motor local y puedes intentarlo de nuevo.',
    'assets.filter': 'Filtrar por riesgo',
    'assets.filter.all': 'Todos',
    'assets.col.ip': 'IP',
    'assets.col.os': 'Sistema',
    'assets.col.ports': 'Puertos',
    'assets.col.cves': 'CVEs',
    'assets.col.risk': 'Riesgo',
    'assets.col.lastScan': 'Ultimo analisis',
    'assets.view': 'Ver',

    'agent.title': 'Asistente de Seguridad',
    'agent.key.change': 'Cambiar clave',
    'agent.key.setup.title': 'Conectar con Claude',
    'agent.key.setup.body': 'Ingresa tu API key de Anthropic para usar el asistente de seguridad interactivo.',
    'agent.key.setup.placeholder': 'sk-ant-...',
    'agent.key.setup.connect': 'Conectar',
    'agent.empty.title': 'Hola, soy NetSentinel',
    'agent.empty.body': 'Puedo analizar tu red, detectar vulnerabilidades y explicar los resultados en lenguaje claro.',
    'agent.suggest.scan': 'Analiza mi red',
    'agent.suggest.history': 'Ultimo analisis',
    'agent.suggest.vulns': 'Dispositivos vulnerables',
    'agent.input.placeholder': 'Escribe tu pregunta...',
    'agent.error.connection': 'Error de conexion. Verifica que el sistema este activo.',

    'tutorial.title': 'Tutorial',
    'tutorial.subtitle': 'Aprende a usar NetSentinel paso a paso.',
    'tutorial.eyebrow': 'Guia para usuarios',
    'tutorial.hero.title': 'Usa NetSentinel sin tocar configuraciones tecnicas',
    'tutorial.hero.body': 'La app prepara el motor local, detecta tu red, ejecuta el analisis y convierte los resultados en acciones claras.',
    'tutorial.practice': 'Iniciar tutorial practico',
    'tutorial.step.scan.title': 'Analiza tu red',
    'tutorial.step.scan.body': 'Selecciona la red detectada, elige el nivel de revision y deja que NetSentinel haga el trabajo pesado.',
    'tutorial.step.results.title': 'Lee el diagnostico',
    'tutorial.step.results.body': 'Los resultados priorizan que debes hacer primero y esconden detalles tecnicos hasta que quieras verlos.',
    'tutorial.step.track.title': 'Da seguimiento',
    'tutorial.step.track.body': 'Usa historial, panel y comparacion para entender como cambia la seguridad de tu red con el tiempo.',
    'tutorial.tips.title': 'Consejos rapidos',
    'tutorial.tip.one': 'Empieza con Rapido si solo quieres confirmar que todo funciona.',
    'tutorial.tip.two': 'Usa Completo cuando puedas dejar la computadora trabajando mas tiempo.',
    'tutorial.tip.three': 'Si algo falla, NetSentinel intentara repararse y te mostrara una explicacion clara.',
    'tutorial.exit': 'Salir',
    'tutorial.back': 'Atras',
    'tutorial.next': 'Siguiente',
    'tutorial.finish': 'Finalizar',
    'tutorial.targetMissing': 'Este paso necesita que la pantalla termine de cargar. Espera un momento o avanza al siguiente paso.',

    'credits.eyebrow': 'Creador del proyecto',
    'credits.role': 'Desarrollador de NetSentinel, una app local de analisis de seguridad de red enfocada en usuarios no tecnicos.',
    'credits.project.title': 'Sobre NetSentinel',
    'credits.project.body': 'NetSentinel integra una interfaz de escritorio, un backend local, almacenamiento propio y un motor seguro de escaneo para convertir herramientas complejas de seguridad en una experiencia guiada y comprensible.',
    'credits.stack.title': 'Tecnologias',
    'credits.focus.title': 'Enfoque del proyecto',
    'credits.focus.one': 'Automatizar preparacion, diagnostico y recuperacion local.',
    'credits.focus.two': 'Explicar riesgos de seguridad en lenguaje claro.',
    'credits.focus.three': 'Mantener detalles tecnicos disponibles sin obligar al usuario a entenderlos.',
    'credits.contact.title': 'Contacto',
    'credits.contact.body': 'Datos pensados para la presentacion del portafolio y futuras demos del proyecto.',
  },
  en: {
    'nav.newScan': 'Scan',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'History',
    'nav.assets': 'Devices',
    'nav.compare': 'Compare',
    'nav.agent': 'AI Assistant',
    'nav.tutorial': 'Tutorial',
    'nav.credits': 'Credits',
    'offline.banner': 'NetSentinel is restarting its local engine. Wait a few seconds or open repair.',
    'offline.setup': 'Repair',
    'error.localService.repairing': 'NetSentinel could not reach its local engine. It is trying to restart it automatically; keep the app open for a few seconds and try again.',
    'error.localService.internal': 'The local engine responded, but hit an internal problem. Try again; if it repeats, open Repair to check the installation.',
    'error.data.notFound': 'I could not find that saved information. It may have been deleted or may not exist yet.',
    'error.scan.notFound': 'I could not find that analysis. It may have been deleted or was not saved completely.',
    'error.scan.engine': 'The analysis engine could not start correctly. NetSentinel is trying to recover it; if it fails again, open Repair.',
    'error.scan.timeout': 'The analysis took longer than expected. Try the Quick level or check that the network is connected.',
    'error.target.required': 'Choose or type a network before starting the analysis.',
    'error.target.invalid': 'That address does not look valid. Use an IP like 192.168.1.1 or a network like 192.168.1.0/24.',
    'error.generic.withRetry': 'The action could not be completed. Try again; if it repeats, use Repair so NetSentinel can check its local engine.',

    'setup.checking': 'Checking whether your computer is ready...',
    'setup.missing.title': 'Complete NetSentinel installation',
    'setup.missing.body': 'NetSentinel will automatically install the local engine that analyzes your network. Everything runs on this computer and no scan data is uploaded.',
    'setup.installing.title': 'Installing local components...',
    'setup.installing.body': 'This can take several minutes the first time. Keep this window open.',
    'setup.progress.tools': 'Installing analysis tools...',
    'setup.progress.db': 'Preparing local storage...',
    'setup.progress.backend': 'Installing internal service...',
    'setup.progress.sandbox': 'Configuring secure scan engine...',
    'setup.progress.scripts': 'Checking that everything can start...',
    'setup.needs_reboot.title': 'Restart required',
    'setup.needs_reboot.body': 'Required Windows features were enabled. Restart your computer and reopen NetSentinel to continue.',
    'setup.btn.reboot': 'Restart now',
    'setup.error.title': 'Setup could not be completed',
    'setup.error.body': 'NetSentinel could not prepare the local engine automatically. Try again; if it keeps failing, we can review the technical details.',
    'setup.error.uac': 'Setup never started. This usually happens when the administrator permission (UAC) that Windows asks for at launch is cancelled. Try again and accept the permission dialog.',
    'setup.starting.title': 'Starting the local engine',
    'setup.starting.body': 'The engine is already installed. We are turning on the local service; this takes a few seconds.',
    'setup.dep.backend': 'Internal service',
    'setup.dep.sandbox': 'Secure scan engine',
    'setup.dep.api': 'Local application',
    'setup.dep.ready': 'Ready',
    'setup.dep.pending': 'Pending',
    'setup.btn.retry': 'Try again',
    'setup.ready.title': 'All set',
    'setup.ready.body': 'The local engine is ready to analyze your network.',
    'setup.btn.install': 'Complete installation',
    'setup.btn.later': 'Continue without setup',
    'setup.btn.verify': 'Check status now',
    'setup.btn.continue': 'Analyze my network',
    'setup.technical.show': 'Show technical details',
    'setup.technical.hide': 'Hide technical details',
    'setup.nvd.label': 'Speed up vulnerability lookup (optional)',
    'setup.nvd.hint': 'A free NVD API key allows faster vulnerability lookups. NetSentinel still works if you skip it.',
    'setup.nvd.placeholder': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    'setup.nvd.save': 'Save',
    'setup.nvd.saved': 'Saved',

    'scan.title': 'Analyze my network',
    'scan.subtitle': 'Detect security issues in all devices connected to your network',
    'scan.network.detecting': 'Detecting your network...',
    'scan.network.detected': 'Network detected',
    'scan.network.change': 'Change',
    'scan.network.choose': 'Choose the network to analyze',
    'scan.network.retry': 'Detect again',
    'scan.network.none': 'No network detected automatically.',
    'scan.manual.label': 'Network address or device',
    'scan.manual.placeholder': '192.168.1.0/24  or  192.168.1.1',
    'scan.manual.hint': 'Type your router IP or your network range',
    'scan.manual.link': 'Enter manually',
    'scan.start': 'Analyze my network',
    'scan.error.invalidTarget': 'Letters, numbers, dots and dashes only',
    'scan.error.startFailed': 'I could not start the analysis. NetSentinel will check its local engine and you can try again in a few seconds.',
    'scan.error.scanFailed': 'The analysis could not be completed. Try the Quick level; if it fails again, open Repair.',
    'scan.error.lostConnection': 'NetSentinel lost contact with its local engine. It is already trying to restart it automatically.',
    'results.error.loadFailed': 'I could not load this result. The analysis may no longer exist or the local engine may be restarting.',
    'offline.dot': 'Backend unreachable',
    'scan.cancel': 'Cancel',
    'scan.newScan': 'New analysis',
    'scan.step.searching': 'Looking for devices on your network...',
    'scan.step.found': 'Devices found — checking security...',
    'scan.step.checking': 'Checking vulnerability database...',
    'scan.step.analyzing': 'Preparing your security report...',
    'scan.step.web': 'Analyzing web services...',
    'scan.showDetails': 'Show technical details',
    'scan.hideDetails': 'Hide details',

    'results.risk.critical': 'Your network has critical issues',
    'results.risk.critical.sub': 'Requires immediate attention to protect your business',
    'results.risk.high': 'Your network has significant risks',
    'results.risk.high.sub': 'Act soon to protect your data and devices',
    'results.risk.medium': 'Your network has some issues',
    'results.risk.medium.sub': 'Review the recommendations below',
    'results.risk.low': 'Your network looks good',
    'results.risk.low.sub': 'Only minor details to review',
    'results.risk.info': 'Your network is secure',
    'results.risk.info.sub': 'No security issues found',
    'results.hero.devices': 'device(s) analyzed',
    'results.hero.issues': 'issue(s) found',

    'results.whattodo': 'What to do',
    'results.problems': 'Issues found',
    'results.noproblems': 'No security issues found on your network.',
    'results.technical.toggle': 'View technical details',
    'results.technical.hide': 'Hide technical details',
    'results.technical.title': 'Technical details — Devices and ports',
    'results.scanDate': 'Scan from',
    'results.duration': 'Duration',

    'severity.critical': 'Critical',
    'severity.high': 'High',
    'severity.medium': 'Medium',
    'severity.low': 'Low',
    'severity.info': 'Info',

    'results.back': 'Back',
    'results.live.scanning': 'Analyzing your network...',
    'results.live.starting': 'Starting analysis...',
    'results.loading': 'Loading results...',
    'results.noHosts': 'No devices discovered in this scan.',
    'results.noPorts': 'No ports reported.',
    'results.col.port': 'Port',
    'results.col.state': 'State',
    'results.col.service': 'Service',
    'results.col.version': 'Version',
    'results.col.cves': 'Vulnerabilities',
    'results.mac': 'MAC',
    'results.vendor': 'Vendor',
    'results.openPorts': 'active service(s)',
    'results.cves': 'vulnerability(ies)',
    'results.webFindings': 'web finding(s)',
    'results.web.title': 'Web findings',

    'history.title': 'Analysis history',
    'history.scans': 'analyses',
    'history.loading': 'Loading...',
    'history.empty': 'No analyses recorded yet.',
    'history.startFirst': 'Run your first analysis',
    'history.col.target': 'Network scanned',
    'history.col.status': 'Status',
    'history.col.started': 'Date',
    'history.col.duration': 'Duration',
    'history.prev': 'Previous',
    'history.next': 'Next',
    'history.delete': 'Delete',
    'history.error': 'I could not load the history. NetSentinel will check its local engine and you can try again in a few seconds.',

    'status.pending': 'Starting',
    'status.running': 'Analyzing',
    'status.completed': 'Completed',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',

    'scan.profile.label': 'Analysis level',
    'scan.profile.quick': 'Quick',
    'scan.profile.quick.hint': 'Quick review of the most common checks',
    'scan.profile.standard': 'Standard',
    'scan.profile.standard.hint': 'Balanced for most networks',
    'scan.profile.full': 'Complete',
    'scan.profile.full.hint': 'Deep review, can take a while',

    'results.export.pdf': 'Export as PDF',
    'results.export.json': 'Export as JSON',
    'results.export.csv': 'Export as CSV',

    'results.finding.status.open': 'Open',
    'results.finding.status.acknowledged': 'Acknowledged',
    'results.finding.status.false_positive': 'False positive',
    'results.finding.status.resolved': 'Resolved',

    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Summary of all scans performed',
    'dashboard.loading': 'Loading...',
    'dashboard.error': 'I could not load the dashboard. NetSentinel will check its local engine and you can try again in a few seconds.',
    'dashboard.stat.totalScans': 'Total scans',
    'dashboard.stat.completed': 'Completed',
    'dashboard.stat.hosts': 'Devices',
    'dashboard.stat.cves': 'Vulnerabilities',
    'dashboard.stat.avgRisk': 'Avg. risk score',
    'dashboard.stat.active': 'Active',
    'dashboard.cvesByLevel': 'Vulnerabilities by level',
    'dashboard.recentScans': 'Recent scans',
    'dashboard.noScans': 'No scans yet. Run your first scan.',
    'dashboard.hosts': 'device(s)',

    'compare.title': 'Compare scans',
    'compare.subtitle': 'Compare two scans to see how your network changed',
    'compare.scanA': 'Scan A',
    'compare.scanB': 'Scan B',
    'compare.choose': 'Select...',
    'compare.run': 'Compare',
    'compare.new': 'New',
    'compare.resolved': 'Resolved',
    'compare.persistent': 'Persistent',
    'compare.noFindings': 'Both scans are identical — no differences found.',
    'compare.error': 'I could not compare those analyses. Check that both exist and try again.',

    'assets.title': 'Devices',
    'assets.subtitle': 'All devices detected across your scans',
    'assets.loading': 'Loading...',
    'assets.empty': 'No devices recorded yet. Run a scan first.',
    'assets.error': 'I could not load the saved devices. NetSentinel will check its local engine and you can try again.',
    'assets.filter': 'Filter by risk',
    'assets.filter.all': 'All',
    'assets.col.ip': 'IP',
    'assets.col.os': 'OS',
    'assets.col.ports': 'Ports',
    'assets.col.cves': 'CVEs',
    'assets.col.risk': 'Risk',
    'assets.col.lastScan': 'Last scan',
    'assets.view': 'View',

    'agent.title': 'Security Assistant',
    'agent.key.change': 'Change key',
    'agent.key.setup.title': 'Connect to Claude',
    'agent.key.setup.body': 'Enter your Anthropic API key to use the interactive security assistant.',
    'agent.key.setup.placeholder': 'sk-ant-...',
    'agent.key.setup.connect': 'Connect',
    'agent.empty.title': 'Hi, I am NetSentinel',
    'agent.empty.body': 'I can scan your network, detect vulnerabilities, and explain results in plain language.',
    'agent.suggest.scan': 'Scan my network',
    'agent.suggest.history': 'Last scan',
    'agent.suggest.vulns': 'Vulnerable devices',
    'agent.input.placeholder': 'Type your question...',
    'agent.error.connection': 'Connection error. Make sure the system is running.',

    'tutorial.title': 'Tutorial',
    'tutorial.subtitle': 'Learn how to use NetSentinel step by step.',
    'tutorial.eyebrow': 'User guide',
    'tutorial.hero.title': 'Use NetSentinel without touching technical settings',
    'tutorial.hero.body': 'The app prepares the local engine, detects your network, runs the analysis, and turns results into clear actions.',
    'tutorial.practice': 'Start practical tutorial',
    'tutorial.step.scan.title': 'Analyze your network',
    'tutorial.step.scan.body': 'Select the detected network, choose the review level, and let NetSentinel handle the heavy work.',
    'tutorial.step.results.title': 'Read the diagnosis',
    'tutorial.step.results.body': 'Results prioritize what to do first and keep technical details hidden until you want them.',
    'tutorial.step.track.title': 'Track progress',
    'tutorial.step.track.body': 'Use history, dashboard, and comparison to understand how your network security changes over time.',
    'tutorial.tips.title': 'Quick tips',
    'tutorial.tip.one': 'Start with Quick if you only want to confirm everything works.',
    'tutorial.tip.two': 'Use Complete when you can leave the computer working longer.',
    'tutorial.tip.three': 'If something fails, NetSentinel will try to repair itself and show a clear explanation.',
    'tutorial.exit': 'Exit',
    'tutorial.back': 'Back',
    'tutorial.next': 'Next',
    'tutorial.finish': 'Finish',
    'tutorial.targetMissing': 'This step needs the screen to finish loading. Wait a moment or move to the next step.',

    'credits.eyebrow': 'Project creator',
    'credits.role': 'Developer of NetSentinel, a local network security analysis app focused on non-technical users.',
    'credits.project.title': 'About NetSentinel',
    'credits.project.body': 'NetSentinel combines a desktop interface, local backend, private storage, and secure scan engine to turn complex security tools into a guided and understandable experience.',
    'credits.stack.title': 'Technologies',
    'credits.focus.title': 'Project focus',
    'credits.focus.one': 'Automate local setup, diagnosis, and recovery.',
    'credits.focus.two': 'Explain security risks in clear language.',
    'credits.focus.three': 'Keep technical details available without forcing the user to understand them.',
    'credits.contact.title': 'Contact',
    'credits.contact.body': 'Information prepared for the portfolio presentation and future demos of the project.',
  },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private static readonly KEY = 'ns_lang';

  lang = signal<'es' | 'en'>(
    (localStorage.getItem(LangService.KEY) as 'es' | 'en') ?? 'en'
  );

  toggle(): void {
    const next = this.lang() === 'es' ? 'en' : 'es';
    this.lang.set(next);
    localStorage.setItem(LangService.KEY, next);
  }

  t(key: string): string {
    return TR[this.lang()][key] ?? key;
  }
}
