import { Injectable, signal } from '@angular/core';

const TR: Record<'es' | 'en', Record<string, string>> = {
  en: {
    'nav.newScan': 'New Scan',
    'nav.history': 'History',
    'nav.settings': 'Settings',
    'offline.banner': 'Backend unreachable — make sure the backend is running on port 8080',
    'scan.title': 'New Scan',
    'scan.subtitle': 'Run an nmap scan against a target host or network range',
    'scan.target.label': 'Target',
    'scan.target.placeholder': '192.168.1.1  or  10.0.0.0/24  or  hostname',
    'scan.target.hint': 'IP address, CIDR range, or hostname',
    'scan.detect': 'Detect LAN',
    'scan.profile.label': 'Scan Profile',
    'scan.flags.label': 'nmap flags',
    'scan.start': 'Start Scan',
    'scan.cancel': 'Cancel',
    'scan.newScan': 'New Scan',
    'scan.liveProgress': 'Monitor live progress',
    'profile.quick.label': 'Quick Scan',
    'profile.quick.desc': 'Service version detection, T4 timing',
    'profile.deep.label': 'Deep Scan',
    'profile.deep.desc': 'OS detection, scripts, version',
    'profile.custom.label': 'Custom',
    'profile.custom.desc': 'Specify nmap flags manually',
    'history.title': 'Scan History',
    'history.scans': 'scans',
    'history.loading': 'Loading...',
    'history.empty': 'No scans recorded yet.',
    'history.startFirst': 'Start your first scan',
    'history.col.target': 'Target',
    'history.col.status': 'Status',
    'history.col.started': 'Started',
    'history.col.duration': 'Duration',
    'history.prev': 'Previous',
    'history.next': 'Next',
    'results.back': 'History',
    'results.loading': 'Loading results...',
    'results.error': 'Failed to load scan results',
    'results.inProgress': 'Scan in progress',
    'results.liveProgress': 'Monitor live progress',
    'results.hosts': 'host(s)',
    'results.openPorts': 'open port(s)',
    'results.cves': 'CVE(s)',
    'results.noHosts': 'No hosts discovered in this scan.',
    'results.noPorts': 'No ports reported for this host.',
    'results.analysis.title': 'Security Analysis',
    'results.findings': 'Findings',
    'results.recommendations': 'Recommendations',
    'results.col.port': 'Port',
    'results.col.state': 'State',
    'results.col.service': 'Service',
    'results.col.version': 'Version',
    'results.col.cves': 'CVEs',
    'results.mac': 'MAC',
    'results.vendor': 'Vendor',
    'results.ai.title': 'AI Deep Analysis',
    'results.ai.desc': 'Claude will analyze attack paths, chained vulnerabilities, and produce a contextual remediation roadmap.',
    'results.ai.generate': 'Generate AI Report',
    'results.ai.noKeyText': 'Configure your Anthropic API key in',
    'results.ai.noKeyLink': 'Settings',
    'results.ai.noKeyEnd': 'to enable AI-powered cross-host analysis.',
    'results.ai.generating': 'Claude is analyzing your scan data...',
    'results.ai.relatedCves': 'Related CVEs:',
    'results.ai.regenerate': 'Regenerate',
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure optional integrations',
    'settings.lang.title': 'Language',
    'settings.lang.desc': 'Switch the interface language between English and Spanish.',
    'settings.ai.title': 'Claude AI Integration',
    'settings.ai.configured': 'Configured',
    'settings.ai.notConfigured': 'Not configured',
    'settings.ai.desc': 'When configured, a "Generate AI Report" button appears in scan results. Claude performs deep cross-host analysis, attack path reasoning, and context-aware remediation — going beyond the automatic deterministic engine. Your API key is stored locally and never sent to any server except the Anthropic API.',
    'settings.ai.keyLabel': 'Anthropic API Key',
    'settings.ai.keyHint': 'Get your key at console.anthropic.com',
    'settings.ai.saved': 'Saved',
    'settings.ai.clear': 'Clear key',
    'settings.ai.save': 'Save',
    'settings.how.title': 'How AI Analysis Works',
    'settings.how.step1.strong': 'Run a scan',
    'settings.how.step1.text': '— NetSentinel collects hosts, ports, versions, and CVEs automatically',
    'settings.how.step2.strong': 'Deterministic analysis',
    'settings.how.step2.text': '— the built-in engine scores risk, identifies dangerous services, and generates findings with zero AI cost',
    'settings.how.step3.strong': 'AI deep analysis (optional)',
    'settings.how.step3.text': '— Claude receives all scan data and produces cross-host attack paths, chained vulnerability scenarios, and a prioritized remediation roadmap',
    'scan.tip1.title': 'Scan targets',
    'scan.tip1.body': 'Use 192.168.1.0/24 to scan an entire subnet, or a single IP like 192.168.1.1.',
    'scan.tip2.title': 'Choosing a profile',
    'scan.tip2.body': 'Quick Scan detects open ports fast. Deep Scan includes OS detection and CVE matching.',
    'scan.tip3.title': 'Authorization required',
    'scan.tip3.body': 'Only scan networks you own or have explicit written permission to test.',
    'nav.reports': 'Reports',
    'reports.title': 'AI Reports',
    'reports.subtitle': 'AI reports generated from completed scans. Export any report as PDF.',
    'reports.empty': 'No reports yet. Open a completed scan and click "Generate AI Report" to create one.',
    'reports.view': 'View',
    'reports.close': 'Close',
    'reports.pdf': 'Export PDF',
    'reports.delete': 'Delete',
    'reports.risk': 'Risk',
    'reports.noRisk': 'N/A',
  },
  es: {
    'nav.newScan': 'Nuevo Escaneo',
    'nav.history': 'Historial',
    'nav.settings': 'Ajustes',
    'offline.banner': 'Backend no disponible — asegurate de que el backend corre en el puerto 8080',
    'scan.title': 'Nuevo Escaneo',
    'scan.subtitle': 'Ejecuta un escaneo nmap contra un host o rango de red',
    'scan.target.label': 'Objetivo',
    'scan.target.placeholder': '192.168.1.1  o  10.0.0.0/24  o  hostname',
    'scan.target.hint': 'Direccion IP, rango CIDR o hostname',
    'scan.detect': 'Detectar LAN',
    'scan.profile.label': 'Perfil de Escaneo',
    'scan.flags.label': 'Flags de nmap',
    'scan.start': 'Iniciar Escaneo',
    'scan.cancel': 'Cancelar',
    'scan.newScan': 'Nuevo Escaneo',
    'scan.liveProgress': 'Ver progreso en vivo',
    'profile.quick.label': 'Escaneo Rapido',
    'profile.quick.desc': 'Deteccion de servicios, timing T4',
    'profile.deep.label': 'Escaneo Profundo',
    'profile.deep.desc': 'Deteccion de SO, scripts, version',
    'profile.custom.label': 'Personalizado',
    'profile.custom.desc': 'Especifica flags de nmap manualmente',
    'history.title': 'Historial de Escaneos',
    'history.scans': 'escaneos',
    'history.loading': 'Cargando...',
    'history.empty': 'No hay escaneos registrados.',
    'history.startFirst': 'Inicia tu primer escaneo',
    'history.col.target': 'Objetivo',
    'history.col.status': 'Estado',
    'history.col.started': 'Iniciado',
    'history.col.duration': 'Duracion',
    'history.prev': 'Anterior',
    'history.next': 'Siguiente',
    'results.back': 'Historial',
    'results.loading': 'Cargando resultados...',
    'results.error': 'Error al cargar los resultados del escaneo',
    'results.inProgress': 'Escaneo en curso',
    'results.liveProgress': 'Ver progreso en vivo',
    'results.hosts': 'host(s)',
    'results.openPorts': 'puerto(s) abierto(s)',
    'results.cves': 'CVE(s)',
    'results.noHosts': 'No se descubrieron hosts en este escaneo.',
    'results.noPorts': 'No se reportaron puertos para este host.',
    'results.analysis.title': 'Analisis de Seguridad',
    'results.findings': 'Hallazgos',
    'results.recommendations': 'Recomendaciones',
    'results.col.port': 'Puerto',
    'results.col.state': 'Estado',
    'results.col.service': 'Servicio',
    'results.col.version': 'Version',
    'results.col.cves': 'CVEs',
    'results.mac': 'MAC',
    'results.vendor': 'Fabricante',
    'results.ai.title': 'Analisis Profundo con IA',
    'results.ai.desc': 'Claude analizara rutas de ataque, vulnerabilidades encadenadas y producira una hoja de ruta de remediacion contextual.',
    'results.ai.generate': 'Generar Informe IA',
    'results.ai.noKeyText': 'Configura tu clave API de Anthropic en',
    'results.ai.noKeyLink': 'Ajustes',
    'results.ai.noKeyEnd': 'para habilitar el analisis con IA.',
    'results.ai.generating': 'Claude esta analizando los datos del escaneo...',
    'results.ai.relatedCves': 'CVEs relacionados:',
    'results.ai.regenerate': 'Regenerar',
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Configura integraciones opcionales',
    'settings.lang.title': 'Idioma',
    'settings.lang.desc': 'Cambia el idioma de la interfaz entre espanol e ingles.',
    'settings.ai.title': 'Integracion Claude AI',
    'settings.ai.configured': 'Configurada',
    'settings.ai.notConfigured': 'No configurada',
    'settings.ai.desc': 'Cuando esta configurada, aparece un boton "Generar Informe IA" en los resultados. Claude realiza analisis profundo entre hosts, razonamiento de rutas de ataque y remediacion contextual. Tu clave API se almacena localmente y nunca se envia a ningun servidor excepto a la API de Anthropic.',
    'settings.ai.keyLabel': 'Clave API de Anthropic',
    'settings.ai.keyHint': 'Obtén tu clave en console.anthropic.com',
    'settings.ai.saved': 'Guardado',
    'settings.ai.clear': 'Borrar clave',
    'settings.ai.save': 'Guardar',
    'settings.how.title': 'Como Funciona el Analisis IA',
    'settings.how.step1.strong': 'Ejecuta un escaneo',
    'settings.how.step1.text': '— NetSentinel recopila hosts, puertos, versiones y CVEs automaticamente',
    'settings.how.step2.strong': 'Analisis deterministico',
    'settings.how.step2.text': '— el motor integrado puntua el riesgo, identifica servicios peligrosos y genera hallazgos sin costo de IA',
    'settings.how.step3.strong': 'Analisis profundo con IA (opcional)',
    'settings.how.step3.text': '— Claude recibe todos los datos del escaneo y produce rutas de ataque entre hosts, escenarios encadenados y una hoja de ruta de remediacion priorizada',
    'scan.tip1.title': 'Objetivos de escaneo',
    'scan.tip1.body': 'Usa 192.168.1.0/24 para escanear una subred completa, o una IP individual como 192.168.1.1.',
    'scan.tip2.title': 'Elegir perfil',
    'scan.tip2.body': 'Escaneo Rapido detecta puertos abiertos. Escaneo Profundo incluye deteccion de SO y CVEs.',
    'scan.tip3.title': 'Autorizacion requerida',
    'scan.tip3.body': 'Escanea solo redes que te pertenezcan o para las que tengas permiso explicito por escrito.',
    'nav.reports': 'Reportes',
    'reports.title': 'Reportes IA',
    'reports.subtitle': 'Informes IA generados a partir de escaneos completados. Exporta cualquier informe como PDF.',
    'reports.empty': 'No hay reportes aun. Abre un escaneo completado y haz clic en "Generar Informe IA" para crear uno.',
    'reports.view': 'Ver',
    'reports.close': 'Cerrar',
    'reports.pdf': 'Exportar PDF',
    'reports.delete': 'Eliminar',
    'reports.risk': 'Riesgo',
    'reports.noRisk': 'N/A',
  },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private static readonly KEY = 'ns_lang';

  lang = signal<'es' | 'en'>(
    (localStorage.getItem(LangService.KEY) as 'es' | 'en') ?? 'es'
  );

  toggle(): void {
    const next = this.lang() === 'es' ? 'en' : 'es';
    this.lang.set(next);
    localStorage.setItem(LangService.KEY, next);
  }

  t(key: string): string {
    return TR[this.lang()][key] ?? key;
  }
}
