import { Injectable, signal } from '@angular/core';

const TR: Record<'es' | 'en', Record<string, string>> = {
  es: {
    'nav.newScan': 'Escanear',
    'nav.history': 'Historial',
    'offline.banner': 'Servicio no disponible — asegurate de que el backend este corriendo en el puerto 8080',
    'offline.setup': 'Configurar sistema',

    'setup.checking': 'Comprobando requisitos del sistema...',
    'setup.missing.title': 'Faltan componentes del sistema',
    'setup.missing.body': 'NetSentinel necesita estos componentes para funcionar. Se instalan automaticamente en Kali WSL2 — no se sube nada a internet.',
    'setup.installing.title': 'Instalando componentes...',
    'setup.installing.body': 'Se ha abierto una ventana de instalacion. El sistema continuara automaticamente cuando termine.',
    'setup.ready.title': 'Todo listo',
    'setup.ready.body': 'Todos los componentes estan instalados y funcionando.',
    'setup.btn.install': 'Instalar ahora',
    'setup.btn.later': 'Continuar sin instalar',
    'setup.btn.verify': 'Verificar estado ahora',
    'setup.btn.continue': 'Ir al escaner',

    'scan.title': 'Analizar mi red',
    'scan.subtitle': 'Detecta problemas de seguridad en todos los dispositivos conectados a tu red',
    'scan.network.detecting': 'Detectando tu red...',
    'scan.network.detected': 'Red detectada',
    'scan.network.change': 'Cambiar',
    'scan.network.choose': 'Elige la red que quieres analizar',
    'scan.network.retry': 'Volver a detectar',
    'scan.network.none': 'No se detecto ninguna red automaticamente.',
    'scan.manual.label': 'Direccion de red o dispositivo',
    'scan.manual.placeholder': '192.168.1.0/24  o  192.168.1.1',
    'scan.manual.hint': 'Escribe la IP de tu router o el rango de tu red',
    'scan.manual.link': 'Ingresar manualmente',
    'scan.start': 'Analizar mi red',
    'scan.cancel': 'Cancelar',
    'scan.newScan': 'Nuevo analisis',
    'scan.step.searching': 'Buscando dispositivos en tu red...',
    'scan.step.found': 'Dispositivos encontrados — revisando seguridad...',
    'scan.step.checking': 'Consultando base de datos de vulnerabilidades...',
    'scan.step.analyzing': 'Preparando tu diagnostico de seguridad...',
    'scan.step.web': 'Analizando servicios web...',
    'scan.showDetails': 'Ver progreso tecnico',
    'scan.hideDetails': 'Ocultar detalles',

    'results.risk.critical': 'Tu red tiene problemas criticos',
    'results.risk.critical.sub': 'Requiere atencion inmediata para proteger tu negocio',
    'results.risk.high': 'Tu red tiene riesgos importantes',
    'results.risk.high.sub': 'Actua pronto para proteger tus datos y dispositivos',
    'results.risk.medium': 'Tu red tiene algunos problemas',
    'results.risk.medium.sub': 'Revisa las recomendaciones a continuacion',
    'results.risk.low': 'Tu red esta bien',
    'results.risk.low.sub': 'Solo hay detalles menores que revisar',
    'results.risk.info': 'Tu red esta segura',
    'results.risk.info.sub': 'No se encontraron problemas de seguridad',
    'results.hero.devices': 'dispositivo(s) analizado(s)',
    'results.hero.issues': 'problema(s) encontrado(s)',

    'results.whattodo': 'Que debes hacer',
    'results.problems': 'Problemas encontrados',
    'results.noproblems': 'No se encontraron problemas de seguridad en tu red.',
    'results.technical.toggle': 'Ver detalles tecnicos',
    'results.technical.hide': 'Ocultar detalles tecnicos',
    'results.technical.title': 'Detalles tecnicos — Dispositivos y puertos',
    'results.scanDate': 'Analisis del',
    'results.duration': 'Duracion',

    'severity.critical': 'Critico',
    'severity.high': 'Alto',
    'severity.medium': 'Medio',
    'severity.low': 'Bajo',
    'severity.info': 'Info',

    'results.back': 'Volver',
    'results.loading': 'Cargando resultados...',
    'results.noHosts': 'No se encontraron dispositivos en este escaneo.',
    'results.noPorts': 'Sin puertos reportados.',
    'results.col.port': 'Puerto',
    'results.col.state': 'Estado',
    'results.col.service': 'Servicio',
    'results.col.version': 'Version',
    'results.col.cves': 'Vulnerabilidades',
    'results.mac': 'MAC',
    'results.vendor': 'Fabricante',
    'results.openPorts': 'servicio(s) activo(s)',
    'results.cves': 'vulnerabilidad(es)',
    'results.webFindings': 'hallazgo(s) web',
    'results.web.title': 'Hallazgos web',

    'history.title': 'Historial de analisis',
    'history.scans': 'analisis',
    'history.loading': 'Cargando...',
    'history.empty': 'No hay analisis registrados.',
    'history.startFirst': 'Realiza tu primer analisis',
    'history.col.target': 'Red analizada',
    'history.col.status': 'Estado',
    'history.col.started': 'Fecha',
    'history.col.duration': 'Duracion',
    'history.prev': 'Anterior',
    'history.next': 'Siguiente',
    'history.delete': 'Eliminar',
    'history.error': 'No se pudo cargar el historial. Asegurate de que el servidor este activo.',

    'status.pending': 'Iniciando',
    'status.running': 'Analizando',
    'status.completed': 'Completado',
    'status.failed': 'Error',
    'status.cancelled': 'Cancelado',
  },
  en: {
    'nav.newScan': 'Scan',
    'nav.history': 'History',
    'offline.banner': 'Service unavailable — make sure the backend is running on port 8080',
    'offline.setup': 'Configure system',

    'setup.checking': 'Checking system requirements...',
    'setup.missing.title': 'Missing system components',
    'setup.missing.body': 'NetSentinel needs these components to work. They are installed automatically in Kali WSL2 — nothing is uploaded to the internet.',
    'setup.installing.title': 'Installing components...',
    'setup.installing.body': 'An installation window has opened. The system will continue automatically when finished.',
    'setup.ready.title': 'All set',
    'setup.ready.body': 'All components are installed and running.',
    'setup.btn.install': 'Install now',
    'setup.btn.later': 'Continue without installing',
    'setup.btn.verify': 'Check status now',
    'setup.btn.continue': 'Go to scanner',

    'scan.title': 'Analyze my network',
    'scan.subtitle': 'Detect security issues in all devices connected to your network',
    'scan.network.detecting': 'Detecting your network...',
    'scan.network.detected': 'Network detected',
    'scan.network.change': 'Change',
    'scan.network.choose': 'Choose the network to analyze',
    'scan.network.retry': 'Detect again',
    'scan.network.none': 'No network detected automatically.',
    'scan.manual.label': 'Network address or device',
    'scan.manual.placeholder': '192.168.1.0/24  or  192.168.1.1',
    'scan.manual.hint': 'Type your router IP or your network range',
    'scan.manual.link': 'Enter manually',
    'scan.start': 'Analyze my network',
    'scan.cancel': 'Cancel',
    'scan.newScan': 'New analysis',
    'scan.step.searching': 'Looking for devices on your network...',
    'scan.step.found': 'Devices found — checking security...',
    'scan.step.checking': 'Checking vulnerability database...',
    'scan.step.analyzing': 'Preparing your security report...',
    'scan.step.web': 'Analyzing web services...',
    'scan.showDetails': 'Show technical details',
    'scan.hideDetails': 'Hide details',

    'results.risk.critical': 'Your network has critical issues',
    'results.risk.critical.sub': 'Requires immediate attention to protect your business',
    'results.risk.high': 'Your network has significant risks',
    'results.risk.high.sub': 'Act soon to protect your data and devices',
    'results.risk.medium': 'Your network has some issues',
    'results.risk.medium.sub': 'Review the recommendations below',
    'results.risk.low': 'Your network looks good',
    'results.risk.low.sub': 'Only minor details to review',
    'results.risk.info': 'Your network is secure',
    'results.risk.info.sub': 'No security issues found',
    'results.hero.devices': 'device(s) analyzed',
    'results.hero.issues': 'issue(s) found',

    'results.whattodo': 'What to do',
    'results.problems': 'Issues found',
    'results.noproblems': 'No security issues found on your network.',
    'results.technical.toggle': 'View technical details',
    'results.technical.hide': 'Hide technical details',
    'results.technical.title': 'Technical details — Devices and ports',
    'results.scanDate': 'Scan from',
    'results.duration': 'Duration',

    'severity.critical': 'Critical',
    'severity.high': 'High',
    'severity.medium': 'Medium',
    'severity.low': 'Low',
    'severity.info': 'Info',

    'results.back': 'Back',
    'results.loading': 'Loading results...',
    'results.noHosts': 'No devices discovered in this scan.',
    'results.noPorts': 'No ports reported.',
    'results.col.port': 'Port',
    'results.col.state': 'State',
    'results.col.service': 'Service',
    'results.col.version': 'Version',
    'results.col.cves': 'Vulnerabilities',
    'results.mac': 'MAC',
    'results.vendor': 'Vendor',
    'results.openPorts': 'active service(s)',
    'results.cves': 'vulnerability(ies)',
    'results.webFindings': 'web finding(s)',
    'results.web.title': 'Web findings',

    'history.title': 'Analysis history',
    'history.scans': 'analyses',
    'history.loading': 'Loading...',
    'history.empty': 'No analyses recorded yet.',
    'history.startFirst': 'Run your first analysis',
    'history.col.target': 'Network scanned',
    'history.col.status': 'Status',
    'history.col.started': 'Date',
    'history.col.duration': 'Duration',
    'history.prev': 'Previous',
    'history.next': 'Next',
    'history.delete': 'Delete',
    'history.error': 'Could not load history. Make sure the server is running.',

    'status.pending': 'Starting',
    'status.running': 'Analyzing',
    'status.completed': 'Completed',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',
  },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private static readonly KEY = 'ns_lang';

  lang = signal<'es' | 'en'>(
    (localStorage.getItem(LangService.KEY) as 'es' | 'en') ?? 'es'
  );

  toggle(): void {
    const next = this.lang() === 'es' ? 'en' : 'es';
    this.lang.set(next);
    localStorage.setItem(LangService.KEY, next);
  }

  t(key: string): string {
    return TR[this.lang()][key] ?? key;
  }
}
